spring.application.name=KafkaPayService
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092

# Consumer config
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Important for JSON ? Object conversion
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.kafkapayservice.dto.OrderEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*